language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t edeel89/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true edeel89/react-test npm test

after_success:
 - docker build -t edeel89/multi-client ./client
 - docker build -t edeel89/multi-nginx ./nginx
 - docker build -t edeel89/multi-server ./server
 - docker build -t edeel89/multi-worker ./worker
 #log in docker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
 #push to dockerhub
 - docker push edeel89/multi-client
 - docker push edeel89/multi-nginx
 - docker push edeel89/multi-server
 - docker push edeel89/multi-worker
